### ISSUE TITLE
Error running tests with code coverage

### ISSUE THREAD

**Issue by ognjen-vuceljic** [xixiaofinland/sf.nvim#108]
Hi @xixiaofinland , I faced an issue this morning trying to run the test that included the coverage flag.

Here's the error that I received:

```
{
  "name": "Error",
  "message": "Error describing ApexTestRunResult: The requested resource does not exist",
  "exitCode": 1,
  "context": "Test",
  "stack": "Error: Error describing ApexTestRunResult: The requested resource does not exist\n    at SfCommandError.from (file:///Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/sf-plugins-core/lib/SfCommandError.js:39:16)\n    at Test.catch (file:///Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/sf-plugins-core/lib/sfCommand.js:315:47)\n    at Test._run (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/command.js:306:29)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Config.runCommand (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/config/config.js:424:25)\n    at async run (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/main.js:94:16)\n    at async file:///Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/bin/run.js:15:1",
  "cause": "Error: Error describing ApexTestRunResult: The requested resource does not exist\n    at AsyncTests.describeSObjects (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/apex-node/lib/src/tests/asyncTests.js:424:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AsyncTests.checkRunStatus (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/apex-node/lib/src/tests/asyncTests.js:183:39)\n    at async AsyncTests.reportAsyncResults (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/apex-node/lib/src/tests/asyncTests.js:153:29)\n    at async TestService.reportAsyncResults (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/apex-node/lib/src/tests/testService.js:169:20)\n    at async Test.run (file:///Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/plugin-apex/lib/commands/apex/get/test.js:46:24)\n    at async Test._run (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/command.js:302:22)\n    at async Config.runCommand (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/config/config.js:424:25)\n    at async run (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/main.js:94:16)\n    at async file:///Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/bin/run.js:15:1",
  "warnings": [],
  "code": "1",
  "status": 1,
```
  

What I did:

- opened APEX class and its corresponding test in side-by-side mode
- ran one test method with `<leader>tT` flag 

 Let's keep track of it here, so that we don't overwhelm the previous idea.

Please let me know if there are any settings that I need to update on my side.

**Comment by xixiaofinland** [comment]
We probably have half a day time delay. Try always give the latest commit of sf.nvim and see if the error disappear.

**Comment by xixiaofinland** [comment]
Unless your tests cover many Apex files and the test_result.json is too large, which might take too long to finish?

If you copy the test cmd and send the output to a json file (`> ./temp.json`) in a console command, like this below, what's the content and size of the `temp.json` you get?


```
sf apex run test --tests CrudTest.it_should_not_fail_on_update_due_to_chunking_errors -r human -w 5 -c -o devhub > ./temp.json
```

**Comment by ognjen-vuceljic** [comment]
@xixiaofinland 

The tests run successfully, and terminal shows that the tests are OK, with the expected details, such as uncovered lines, test outcome, etc.

I can see the `cache` filter being created, but it's empty --> the `test_result.json` comes in with significant delay, and gets populated with the following content:

![image](https://github.com/user-attachments/assets/cffbaadc-3463-499f-8c70-837195f5e096)


```
{
  "name": "Error",
  "message": "Error describing ApexTestRunResult: The requested resource does not exist",
  "exitCode": 1,
  "context": "Test",
  "stack": "Error: Error describing ApexTestRunResult: The requested resource does not exist\n    at SfCommandError.from (file:///Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/sf-plugins-core/lib/SfCommandError.js:39:16)\n    at Test.catch (file:///Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/sf-plugins-core/lib/sfCommand.js:315:47)\n    at Test._run (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/command.js:306:29)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Config.runCommand (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/config/config.js:424:25)\n    at async run (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/main.js:94:16)\n    at async file:///Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/bin/run.js:15:1",
  "cause": "Error: Error describing ApexTestRunResult: The requested resource does not exist\n    at AsyncTests.describeSObjects (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/apex-node/lib/src/tests/asyncTests.js:424:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AsyncTests.checkRunStatus (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/apex-node/lib/src/tests/asyncTests.js:183:39)\n    at async AsyncTests.reportAsyncResults (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/apex-node/lib/src/tests/asyncTests.js:153:29)\n    at async TestService.reportAsyncResults (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/apex-node/lib/src/tests/testService.js:169:20)\n    at async Test.run (file:///Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@salesforce/plugin-apex/lib/commands/apex/get/test.js:46:24)\n    at async Test._run (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/command.js:302:22)\n    at async Config.runCommand (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/config/config.js:424:25)\n    at async run (/Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/node_modules/@oclif/core/lib/main.js:94:16)\n    at async file:///Users/Ognjen_Vuceljic/.local/share/sf/client/2.49.7-e83764e/bin/run.js:15:1",
  "warnings": [],
  "code": "1",
  "status": 1,
  "commandName": "Test"
```


I will try this out in different SFDX project structures, to try to understand where the issue might be. I have update `sf` to the latest version.

**Comment by xixiaofinland** [comment]
Are you sure your `sf.nvim` is up-to-date? This looks close to a bug I fixed in the older version. 

In case it is indeed up-to-date, you can try these steps:
1. Copy the "Test Run Id" from the term.  You can see it's `7071n0000Buv0r3` in the screenshot below.
2.  Run this command below (using the copied `id` value) in your console and see if it displays the test result in json format successfully.
```
sf apex get test -i 7071n0000Buv0r3 --json -c
```
3. Save the test result into a local file `temp.json` and view it's content is correct.
```
sf apex get test -i 7071n0000Buv0r3 --json -c > temp.json
```

If all 3 steps above succeed, I don't see the reason the command in Nvim would fail.

![Image 013](https://github.com/user-attachments/assets/ea8fee59-e4e3-4311-bae6-fe295792b58d)

**Comment by ognjen-vuceljic** [comment]
Thank you @xixiaofinland 

This workaround generated positive result for me.  Once I get the test results via `sf apex get test` command, and paste into `test_results.json`, the coverage highlighting works properly.

![Screenshot 2024-07-16 at 22 50 20](https://github.com/user-attachments/assets/be082a4d-3e96-46cb-8608-7c8c1f6854cd)

I've tried out a few more tests (updated to latest version of `sf.nvim`), and in each of them the callback result comes fairly late.  

The terminal shows the execution details fairly quickly, but it takes 1-2 mins for the callback to pass the details to `test_result.json` . 

Just for the sake of statistics and data - on average, a few of my latest tests (when retrieved via `sf apex get test`) produced JSONs that are ~1500 lines long. Not sure if this has any impact on the performance of the coverage highlighting operation, but I thought it might be useful to share some info from project-related context.

Thanks for the hard work on this one!

**Comment by xixiaofinland** [comment]
Do you mean manual running those 3 steps works well but the plugin still hits the error? They are literally doing exactly the same thing.

In the plugin, the save test result and enable sign icon happens here. https://github.com/xixiaofinland/sf.nvim/blob/5eedbc4ea9035768eee03236c0613d665ca02136/lua/sf/test.lua#L80

**Comment by ognjen-vuceljic** [comment]
Yes, that's the weird part in my opinion :) 

Both the plugin code and manual steps perform the same thing, but I have success only when running it manually. It's still great that I can get the coverage as it helps a lot, and I am currently fine with those few extra steps.

Just wondering if there is some weird config issue on my side that makes this `sf apex get test -i ...` command to fail when run via plugin.

**Comment by xixiaofinland** [comment]
it'd be nice to add `print(cmd)` from the line mentioned above, so we know exactly if the command is correct.

how about `SFPullMd` command, can you successfully create those metada files locally?

In the latest commit, I just renamed the `cache` folder to `sf_cache` to store all files of this plugin.

**Comment by xixiaofinland** [comment]
If you still see this error: "The requested resource does not exist", most likely the `Test Run Id` is wrongly retrieved for whatever reason.

Again, if we can `print(cmd)` it'd be easy to diagnose.

**Comment by xixiaofinland** [comment]
do you still have this problem?
