### ISSUE TITLE
bug: push/retrieve commands not working on PowerShell/ Command Prompt

### ISSUE THREAD

**Issue by felipeourives** [xixiaofinland/sf.nvim#171]
Hi @xixiaofinland,

First of all, I would like to congratulate you on this amazing plugin. Finally, I will be able to be free of VSCode while working with Salesforce haha.

I have noticed that using the plugin in PowerShell or the Command Prompt to execute a push or retrieve does not work. It shows a screen like this one:
![Screenshot 2024-07-23 194904](https://github.com/user-attachments/assets/60108c92-e5fc-4c28-bea3-1908a71a509b)

I was testing the plugin a little bit, and I found that in the file `lua/sf/sub/raw_term.lua` at line 64, if it executes the `cmd` directly instead of `cmd_with_echo`, it works, but without the first line that indicates what is being executed, which is very helpful.

Do you think there is a solution for this that could work on Windows + PowerShell and any other OS/Shell?

Once again, thank you for all your work!

**Comment by xixiaofinland** [comment]
Hi @felipeourives, thanks for trying this plugin out :)!

Short answer: if you replace the line in your local installed sf.nvim plugin, does it help? 

```
  local cmd_with_echo = string.format('echo -e " %s";%s', echo_msg, cmd)
```

The echo is meant to display the command visually before executing it. And the color is for visual ease. It seems [the term color codes](https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences) break in PowerShell.

Maybe I can add a configuration setting to disable the color for users in Windows. 

Btw, have you tried `Windows Terminal` app, not sure if it supports better.

**Comment by felipeourives** [comment]
Hey @xixiaofinland, thanks for the quick reply!

So I had test your suggestion and a similar screen happens, but now without the `[0;35m`. The strange part is if i copy the cmd line and try the echo directly in the PowerShell it works (i needed to remove the `-e` bc the echo in PowerShell does not rigorize it). Maybe bc the` echo `cmd in PowerShell is just a alias to `Write-Host` and it executing via nvim terminal cause some strange behavior? idk

**Comment by xixiaofinland** [comment]
ah, right. I thought it was the special chars in the color code messed up.

please try this:

```
cmd_with_echo = string.format('Write-Host "%s" -ForegroundColor Cyan; %s', echo_msg, cmd)
```

**Comment by felipeourives** [comment]
Hey!

I have test it and I got this:

`'Write-Host' is not recognized as an internal or external command,
operable program or batch file.

[Process exited 1]
`

Do you know if that something missing on my config or something like that?

**Comment by felipeourives** [comment]
oh, yeah I am using win11, maybe that can explain the difference. I will try a couple of options and I go back here if I find something that works here.

**Comment by xixiaofinland** [comment]
Meanwhile I close this issue as it doesn't fall into this plugin's support scope.
