### ISSUE TITLE
Overwrite Key Mapping

### ISSUE THREAD

**Issue by nhatquang0672** [xixiaofinland/sf.nvim#215]
Hi team, 

I try to setup the custom key mapping but it doesn't work. 

Example: 

```
return {
  'xixiaofinland/sf.nvim',
  dependencies = {
    'nvim-treesitter/nvim-treesitter',
    'ibhagwan/fzf-lua', -- no need if you don't use listing metadata feature
  },
  config = function()
    require('sf').setup() -- Important to call setup() to initialize the plugin!
    print 'sf.nvim loaded successfully'
    print 'Loading custom keymaps...'
    -- require('custom.sf_keymap').set_default_hotkeys()

    local Sf = require 'sf'
    -- Common hotkeys for all files;
    vim.keymap.set('n', '<leader>fss', Sf.set_target_org, { buffer = true, desc = 'olala' })
  end,
}
```

I also read the documentation but no where to put the custom key mapping config into the setup. 

Thanks.

**Comment by nhatquang0672** [comment]
I figured out this issue related to config buffer=true. If I remove this setting, the mapping keys works fine.
The if condition below isn't working.
```
    if vim.tbl_contains(vim.g.sf.hotkeys_in_filetypes, vim.bo.filetype) then
      -- nmap('<leader>ed', Sf.diff_in_target_org, 'diff in target_org')
    end
```
Another question: Do we have diff folder feature like VSCode ? 

Thanks.

**Comment by xixiaofinland** [comment]
Hi,

I tried the exact config in your original post, the `fss` hotkey works fine for me as expected.
the `buffer = true` shouldn't cause any issue. 

This plugin has only file diff between local and the org. I haven't used folder diff in VSCode. Does it show a list of file names or diffs of file content between the target org and the local folder?

**Comment by xixiaofinland** [comment]
I don't quite follow. 
As you have defined the keys by yourself (like the `fss`) in Lazy's config, they are enabled globally without any condition constraints.

While the `if` condition you mentioned enables the related hotkeys only when the current buffer is one of these filetypes ("apex", "sosl", "soql", "javascript", "HTML"), which is configurable in the settings. 

```
  hotkeys_in_filetypes = {
    "apex", "sosl", "soql", "javascript", "html"
  },
```

> 
> ```
>     if vim.tbl_contains(vim.g.sf.hotkeys_in_filetypes, vim.bo.filetype) then
>       -- nmap('<leader>ed', Sf.diff_in_target_org, 'diff in target_org')
>     end
> ```
> 
> Another question: Do we have diff folder feature like VSCode ?
> 
> Thanks.

**Comment by xixiaofinland** [comment]
The default user-key categories are the most confusing part.
In the readme, it describes as below.

However, as you have default user-key disabled (which is recommended) and supply your own keys, it's all at your control when and what keys you want to expose/activate.

> 
>   -- Some hotkeys are on "project level" thus always enabled. Examples: "set default org", "fetch org info".
>   -- Other hotkeys are enabled when only metadata filetypes are loaded in the current buffer. Example: "push/retrieve current metadata file"
>   -- This list defines what metadata filetypes have the "other hotkeys" enabled.
>   -- For example, if you want to push/retrieve css files, it needs to be added into this list.

**Comment by nhatquang0672** [comment]
Hmm, it's really weird when sf.nvim works fine with my config. 
I follow your codebase to setup my custom mapping.
You can get [my config](https://github.com/nhatquang0672/dotfiles/blob/kickstart/nvim/lua/custom/plugins/sf.lua) in this repo, I use kickstart.nvim as my base config. It still didn't work when I put config buffer=true.

The if condition is not working, because the vim.bo.filetype is aways null. I have to use callback function to make this config works. 
```
return {
  'xixiaofinland/sf.nvim',
  dependencies = {
    'nvim-treesitter/nvim-treesitter',
    'ibhagwan/fzf-lua', -- no need if you don't use listing metadata feature
  },
  config = function()
    -- require('sf').setup { enable_hotkeys = true } -- Important to call setup() to initialize the plugin!
    require('sf').setup()
    local Sf = require 'sf'
    local function set_keymaps()
      local nmap = function(keys, func, desc)
        if desc then
          desc = desc .. ' [Sf]'
        end
        vim.keymap.set('n', keys, func, { desc = desc })
      end

      -- vim.keymap.set('n', '<leader>es', Sf.set_target_org, { desc = 'olala' })
      nmap('<leader>qs', Sf.set_target_org, 'set target_org')
      -- Apply keymaps if filetype is in hotkeys_in_filetypes
      if vim.tbl_contains(vim.g.sf.hotkeys_in_filetypes, vim.bo.filetype) then
        nmap('<leader>qd', Sf.diff_in_target_org, 'diff in target_org')
      end
    end
    -- Set keymaps after buffer is read and filetype is set
    vim.api.nvim_create_autocmd('BufWinEnter', {
      callback = set_keymaps,
    })
  end,
}
```

**Comment by xixiaofinland** [comment]
1. How you define your own keys or how kickstart.nvim impacts your keys are out of my knowledge.

2. Do you mean when you open a `.cls` file, it's not in `apex` type like in the screenshot?  Use `:set filetype` to check.
![Screenshot 2024-08-26 at 13 29 20](https://github.com/user-attachments/assets/67669340-4fb5-434e-8d28-ecafa81e254d)

**Comment by xixiaofinland** [comment]
Do you mean, when you open a `.cls` file, its filetype is not set to `apex`?  Use `:set filetype` to verify it.

![Screenshot 2024-08-26 at 13 29 20](https://github.com/user-attachments/assets/0134e40f-5416-4b52-933f-80e30269d6cf)

**Comment by nhatquang0672** [comment]
Thanks for your support.
