### ISSUE TITLE
Don't completely fail to list md if some failed to be pulled

### ISSUE THREAD

**Issue by FedeAbella** [xixiaofinland/sf.nvim#222]
Here's the issue: Some metadata types are perfectly valid, but only after they've been enabled in an org in some way. e.g.: my company works a lot with Experience sites, and Omnistudio. Once those have been enabled (be it via creating an Experience site, or installing the Omnistudio package), you get some metadata types that are valid for pull and retrieve, such as: `ExperienceBundle`, `OmniDataTransform`, `OmniIntegrationProcedure`. 

But, when those features are not enabled in an org, the `SF md pull` command fails to retrieve and create json files for those. So far, not that big a deal, at most you get an error message which is not a big deal. However, when you try to `SF md list`, since the metadata types are in the config but the json files failed to be created, the entire command fails, and you can't retrieve anything.

I propose we don't have the entire command fail, but list those md to retrieve that it can do so, and maybe show some warning messages for missing types?

**Comment by xixiaofinland** [comment]
I try to reproduce the issue but couldn't.

in the config I have this below, so `SF md pull` retrieves `ExperienceBundle` content into JSON file.

```
            types_to_retrieve = {
                "ApexClass",
                "ApexTrigger",
                "StaticResource",
                "LightningComponentBundle",
                "ExperienceBundle"
            },
```

Despite its JSON is a empty `[]`, "SF md list" remains working to show the list correctly (screenshot).
![Image 019](https://github.com/user-attachments/assets/8f9d2fe6-a990-48fd-a08d-8475baac331d)

**Comment by FedeAbella** [comment]
These are my `types_to_retrieve`:
```lua
            types_to_retrieve = {
                "ApexClass",
                "ApexTrigger",
                "AuraDefinitionBundle",
                "ConnectedApp",
                "CustomApplication",
                "CustomField",
                "CustomMetadata",
                "CustomObject",
                "CustomPermission",
                "CustomTab",
                "ExperienceBundle",
                "ExternalCredential",
                "FlexiPage",
                "Flow",
                "Layout",
                "LightningComponentBundle",
                "LightningMessageChannel",
                "NamedCredential",
                "OmniDataTransform",
                "OmniIntegrationProcedure",
                "PermissionSetGroup",
                "PermissionSet",
                "Profile",
                "QuickAction",
                "RecordType",
                "Role",
                "Settings",
                "SharingCriteriaRule",
                "SharingOwnerRule",
                "StaticResource",
            },
```

This is what I get when I run `SF md pull`:
![image](https://github.com/user-attachments/assets/6fb74639-5330-4f40-801c-409e0c3934bc)

After which, none of the files for the failed types are there:
![image](https://github.com/user-attachments/assets/878cd21a-8a6b-4e8b-996f-ef7ac716417b)

And this happens when I run `SF md list`:
![image](https://github.com/user-attachments/assets/8577456f-9bb8-4a3c-a4db-d36c606f7cf2)

**Comment by FedeAbella** [comment]
Wait, I just noticed there's a double slash in the original error message for retrieve failed :thinking: Could that be a hint for something going on?

**Comment by FedeAbella** [comment]
So, it looks like the main difference here is you have an empty file for those md types that failed to retrieve, but I don't. Are we sure in your case the md type failed to retrieve entirely? Or is it possible it didn't fail, there was just no md to pull?

Could you try with the Omnistudio types? Those are more likely to just fail to retrieve at all

**Comment by FedeAbella** [comment]
This is what I get when I try to run the pull command myself on the cli (this is a trailhead playground):
![image](https://github.com/user-attachments/assets/0cc61cd4-26db-4ae6-8a7c-430ca5df21ff)

So my hypothesis here is I'm getting full on errors on the pull, which cause the file not to get created, but you're just pulling empty md, which results in empty (but existing) files

**Comment by xixiaofinland** [comment]
With your list, I also encounter the two error:
![Image 022](https://github.com/user-attachments/assets/fbca3cf4-8a1d-47c4-b7be-20409361d03f)

I made a fix: SF md list will now show a warning for missing JSON files only once per Nvim session, and remain silent afterward. The warning is shown just once because if there are multiple lines in :messages, it blocks user actions, requiring you to press space to continue.

![Image 021](https://github.com/user-attachments/assets/65529e7d-aa8c-40e2-8794-3870043d5e70)

However, wouldn't it be better to remove the two md types from your  `types_to_retrieve`  since the sf CLI doesn't allow you to download them anyway?

**Comment by FedeAbella** [comment]
Thanks! That's really helpful! ❤️

The CLI actually allows you to download those types, **if** they're enabled in the org, which is why I have them there. Most of the projects in my company use those, since we specialize in Health Cloud and Omnistudio. I'm on my phone now, but I'll share a screenshot tomorrow 😁

**Comment by FedeAbella** [comment]
Ok, so here's the `sf-cache` directory after pulling from an org with Omnistudio enabled (and Experience sites as well):
![2024-09-12_10-19-02](https://github.com/user-attachments/assets/88f55124-5c88-44ac-abe4-9b2d906c736e)

So if the org is enabled for those kinds of metadata, you can definitely pull it, and you'll get the json files populated:
![2024-09-12_10-20-49](https://github.com/user-attachments/assets/1c5ee0dc-6f20-4efb-b00e-85eeddfde4ec)

And you can pull those files with `SF md list` too:
![2024-09-12_10-25-04](https://github.com/user-attachments/assets/dd2eb58d-7989-4b37-9e23-ec2c129fe129)

In any case, this now works great even in orgs where that md is not enabled, so thanks so much! I'm closing this now
