### ISSUE TITLE
fzf-lua previews of md change order every time nvim is run

### ISSUE THREAD

**Issue by FedeAbella** [xixiaofinland/sf.nvim#234]
I just noticed this while building the logs feature. `fzf-lua` preview windows, e.g. when using `SF md list`, have the table key,value pairs in a different order every time nvim is run. I hadn't noticed that before, and can't really tell why it's happening. My best guess is that `vim.json.decode` is returning a table in a different order each time, but can't think why that would be the case. 

![image](https://github.com/user-attachments/assets/4d8b122b-fcf5-47bb-9ff6-b5c9d6908269)

![image](https://github.com/user-attachments/assets/b2d4f014-7d41-42fe-8017-647b32902bf4)

![image](https://github.com/user-attachments/assets/d062446b-096e-474e-86bc-146a7114bdcb)

**Comment by xixiaofinland** [comment]
interesting, I didn't even noticed this. In rare cases, I need to eyeball the `lastModifiedDate` or `lastModifiedByName`. I don't really know, probably you need to ask from fzf-lua?

**Comment by FedeAbella** [comment]
I'm currently looking into it, which is how I ran into that other formatting issue. I'm trying to see where the table loses it's order

**Comment by FedeAbella** [comment]
It looks like the issue is with lua's `print` command, which does not follow the table's "printed" order:
![2024-09-27_17-25-08](https://github.com/user-attachments/assets/708d7bc0-f47f-405f-94e9-a03b972b1ce5)

I'm going to see if there's some other way we can accomplish that. I've tried pushing `vim.inspect` into `fzf-lua`'s contents table, but unfortunately it means the preview windows shows a full table, braces and all (though it does respect order)
