### ISSUE TITLE
Proposal: If user has auto display code test signs, have them enabled by default on startup

### ISSUE THREAD

**Issue by FedeAbella** [xixiaofinland/sf.nvim#247]
Maybe you thought this out differently @xixiaofinland, but to me, if I have code coverage signs on by default (so, auto show when a test runs), I'd expect those to also be shown when first starting up. This way, if maybe I left work and resumed next day, and want to continue from where I was before, I don't need to toggle them on.

Did you maybe have something else in mind by having them disabled by default on startup?

**Comment by xixiaofinland** [comment]
Your suggestion is wise, I don't have any hidden reason not to do so.
It's a feature requested by others and I don't use it as often. It definitely has areas to improve.

Feel free to make a PR :).
