### ISSUE TITLE
Feature request: ability to deploy code with the --ignore-conflicts flag

### ISSUE THREAD

**Issue by wspringe** [xixiaofinland/sf.nvim#251]
There are many times where I simply cannot deploy my code to my sandbox without that flag because of how my org is set up in my company. This would be a welcome feature so that I do not have to turn to a terminal each time to deploy my changes.

**Comment by wspringe** [comment]
I can also look into adding this myself as a contribution :)

**Comment by xixiaofinland** [comment]
It totally makes sense to allow users to defineextra parameters on the fly in their keybindings.

Do you use `save_and_push()` or `push_delta()`? @wspringe 

I consider updating it like this below. What's your thought? @FedeAbella 

```
function Term.save_and_push(extra_params)
  if U.is_empty_str(U.target_org) then
    return U.show_err("Target_org empty!")
  end
  vim.api.nvim_command("write!")
  
  local cmd_builder = B:new():cmd("project"):act("deploy start"):addParams("-d", "%:p")
  if extra_params then
    cmd_builder:addParamStr(extra_params)
  end

  local cmd = cmd_builder:build()
  t:run(cmd)
end
```

Then key as:

```
local nmap = function(keys, func, desc)
  if desc then
    desc = desc .. " [Sf]"
  end
  vim.keymap.set("n", keys, func, { buffer = true, desc = desc })
end

local Sf = require("sf")
nmap("<leader>sp", function() Sf.save_and_push("--force-ignore") end, "push current file with force-ignore")

```

**Comment by FedeAbella** [comment]
I don't see any references to a `--force-ignore` flag in the `sf` docs. Can you point me to a reference of it and how it's used @wspringe ? Could you also provide an example command where you use it? Thanks!

**Comment by wspringe** [comment]
Oh my, I meant the `—ignore-conflicts` flag. Sorry about that!

**Comment by wspringe** [comment]
@xixiaofinland I mainly use the `save_and_push()` command.

**Comment by FedeAbella** [comment]
Ah, yes! That one I **do** know. @xixiaofinland I think we can safely add the option of passing a string of extra params to both `save_and_push` and `push_delta`. I'd go as far as to say we can safely add it to `retrieve` commands as well. I wonder if in the future we could support accepting a table of params, but I guess we can go with a string for now.

What I would not recommend is adding the `--ignore-conflicts` flag to the default key mapping. Given that's basically like force pushing in git, I find it's too aggressive to have as a default, and should rather be a conscious choice by who's using the command. People can add their own keymaps if they want quick access to it. Alternatively, we **could** create a _separate_ keymap for force-pushing, if you feel it's important to expose it as such.

If that's ok with you, I think we can apply your first proposed solution to those commands.

@wspringe would that work for you?

**Comment by FedeAbella** [comment]
@xixiaofinland added this really quickly @wspringe. It's up on `main`. Enjoy!

**Comment by xixiaofinland** [comment]
Custom keys can be defined as example:

```
        local Sf = require("sf")
        vim.keymap.set('n', '<leader>s4', function() Sf.save_and_push('-c') end, { desc = 'test4' })
        vim.keymap.set('n', '<leader>s5', function() Sf.push_delta('-c') end, { desc = 'test5' })
        vim.keymap.set('n', '<leader>s6', function() Sf.retrieve('-c') end, { desc = 'test6' })
        vim.keymap.set('n', '<leader>s7', function() Sf.retrieve_delta('-c') end, { desc = 'test7' })
```
