### ISSUE TITLE
Add `LICENSE.md` for `MIT` license

### ISSUE THREAD

**Issue by mirabtellegen** [xixiaofinland/sf.nvim#255]
Hi, I am familiar with your project and I noticed that it does not have a license. I would like to suggest that you add a license to your project so it can be freely used, modified, repurposed, or shared by the open source community. You can find information on various licenses [here](https://opensource.org/licenses). To choose the right license for your project, check out [choosealicense.com](https://choosealicense.com/).

I see in the `README.md` that you mention `MIT`. It seems like you are considering applying this license, but GitHub currently doesn't recognize these references in your repository. To apply this license in a way that the community can recognize, you can add a file in the root directory of your default branch named `LICENSE.md` containing your license.

**Comment by xixiaofinland** [comment]
Thanks, done!
