### ISSUE TITLE
Stuff is appended to layout file names when retrieving layout

### ISSUE THREAD

**Issue by FedeAbella** [xixiaofinland/sf.nvim#257]
I'm leaving this here as I just ran into it. I can take a look at it at some point:

I was trying to retrieve a layout using `SF md list` and it failed to retrieve it even though it was listed because `SF md pull` pulled it correctly. I noticed there's something weird with the filename it's trying to retrieve:
![image](https://github.com/user-attachments/assets/f7583096-9708-4570-81ef-2bcde3c26416)

It's as though part of the filename is appended after the extension.

**Comment by FedeAbella** [comment]
Found it weird that it didn't happen with a previous layout I pulled, so I restarted neovim, and tried again, and it worked now:

![image](https://github.com/user-attachments/assets/6db374be-10eb-4ca4-a806-637031648a04)

I'm actually now thinking there's something going on with the `%` in the layout metadata name being expanded when a file is open. I'll look into it.

**Comment by xixiaofinland** [comment]
layout names were the most eccentric in SF meta-data files, most probably there were special chars in the name triggered the expansion.

Let's see if you can reproduce it in the future.

**Comment by FedeAbella** [comment]
Yeah, layouts are a headache... I'll keep poking around and see what I can come up with

**Comment by FedeAbella** [comment]
Ok, so I figured out what's going on:

We're expanding parameter values (as intended), but in some cases, these parameter values can contain the `%` character (such as, names for layouts where the object name has an encoded char, annoying). This was causing the name retrieved from the md list to be expanded further, introducing the current buffer path in the middle of the name.

I've created a PR where we allow params to **not** be expanded, by adding some verbosity to how the param is added to `cmd_builder`. I've made it so that the extra verbosity is only needed when actively suppressing expansion, meaning all other commands still work the same with the same syntax.

Let me know what you think @xixiaofinland

**Comment by FedeAbella** [comment]
One note @xixiaofinland: This will solve the issue for `SF md list`, but not for other commands (like, using `save_and_push` from a layout file with an `%` in the filename). This is because in nvim itself, running `vim.fn.expandcmd("%:p")` on a buffer with a `%` in the filename causes the filename to be recursively inserted in the middle. I'll see about raising an issue with them tomorrow about this.
