### ISSUE TITLE
Allow setting the wait time for sf commands in config

### ISSUE THREAD

**Issue by FedeAbella** [xixiaofinland/sf.nvim#258]
Just ran into this: Tried to run a single test method, but for some reason the org took forever to actually run the test (it just stayed there in the queue), which caused the command to fail. I can see this happening also in big orgs with lots of stuff, or environments where multiple developers are working.

We could allow the plugin config to set a custom wait value to use with the `-w` flag, and default to the current 5.

**Comment by FedeAbella** [comment]
No, you're right. Maybe I wasn't clear enough. I meant the default of 5 is not long enough for some orgs, where a single test can be in a queue for much longer. 

So allowing the user to set a time in the config (and leaving the default at 5), would allow them to increase the time if they run into one of these orgs.

**Comment by xixiaofinland** [comment]
I see. I agree we should allow users to define the waiting time according to their specific demands.
I will take a look at the PR when I get the time.
