### ISSUE TITLE
Error on ':SF md pull'

### ISSUE THREAD

**Issue by basham00** [xixiaofinland/sf.nvim#266]
I'm receiving the following error while executing 'SF md pull'

Error executing Lua callback: Vim:E739: Cannot create directory /C:/Users/Anon/Documents/SalesforceDev/TestProject/sf_cache: invalid argument
stack traceback:
	[C]: in function 'mkdir'
	...non/AppData/Local/nvim-data/lazy/sf.nvim/lua/sf/util.lua:67: in function 'create_plugin_folder_if_not_exist'
	.../Anon/AppData/Local/nvim-data/lazy/sf.nvim/lua/sf/md.lua:139: in function 'pull_metadata'
	.../Anon/AppData/Local/nvim-data/lazy/sf.nvim/lua/sf/md.lua:128: in function 'pull_md_json'
	.../Anon/AppData/Local/nvim-data/lazy/sf.nvim/lua/sf/md.lua:9: in function 'func'
	...vim-data/lazy/sf.nvim/lua/sf/sub/config_user_command.lua:23: in function 'impl'
	...vim-data/lazy/sf.nvim/lua/sf/sub/config_user_command.lua:126: in function <...vim-data/lazy/sf.nvim/lua/sf/sub/config_user_command.lua:114>

I was poking around a bit trying to understand the issue more and here are the findings I find may be relevant:

sf/util.lua line 66 calls `vim.fn.isdirectory(cache_folder)` and for some reason:

- Manually executing `:lua vim.fn.isdirectory(require'sf.util'.get_plugin_folder_path())` always returns 0 even if I manually create the folder in the correct path
- Manually executing `:lua vim.fn.isdirectory("C:/Users/Anon/Documents/SalesforceDev/TestProject/sf_cache")` works as expected

Manually executing `:lua vim.fn.mkdir("C:/Users/Anon/Documents/SalesforceDev/TestProject/sf_cache")` creates the folder as expected

Manually executing `:lua print(require'sf.util'.get_plugin_folder_path())` successfully prints "/C:/Users/Anon/Documents/SalesforceDev/TestProject/sf_cache"

Not sure if this is a bug or incompatibility with windows.

**Comment by xixiaofinland** [comment]
Hi, thanks for trying it out!

The code in this plugin is Linux-centric, as it assumes paths begin with `/`, which isn’t valid in Windows where paths often start with a drive letter, e.g., `C:\`.

I don't have a desire to support Windows but simple PRs might be welcomed.

A possible solution is to manually create the "sf_cache" folder in your project.
