### ISSUE TITLE
Scratch Org Development

### ISSUE THREAD

**Issue by waltonzt** [xixiaofinland/sf.nvim#47]
Hello @xixiaofinland 

I am a SF developer who recently started using neovim so naturally I came across this plugin. I really like the idea and the implementation but it does not seem to work for scratch org development. Since this is the main org type that I develop towards I forked this repo and was able to make a simple change to allow scratch orgs to be selected as the target_org.

Is this something that you are interested in including in your plugin?

I also planned to add some more functionality that fits my specific workflow but I could contribute that as well if interested. I figured I would reach out and see what you thoughts are. No worries if that does not fit your idea for this.

**Comment by xixiaofinland** [comment]
Hi @waltonzt ,

I'm glad this tool is adding value for you!

My current work doesn't use scratch orgs, so I haven't had the chance to implement it. Yes, please feel free to create a PR for this feature.

As a rule of thumb for PRs: consider if the feature is common among Salesforce developers. If it exists in Salesforce VSCode plugins, it's probably a good candidate. We can always converse before the PRs :).
