### ISSUE TITLE
Plugin doesn't work in Neovim version 0.9.5

### ISSUE THREAD

**Issue by Makary01** [xixiaofinland/sf.nvim#73]
#### Description
When I installed the plugin with Neovim in version 0.9.5 I couldn't use any commands and when I executed the command `:lua require'sf.util'.get_sf_root()` from README.md results in the error message in line 34 of the file [sf.nvim/lua/sf/util.lua](https://github.com/xixiaofinland/sf.nvim/blob/983955eec56034b57b119428b0c8832b7c817603/lua/sf/util.lua):
```
E5108: Error executing lua [string ":lua"]:1: attempt to index field 'uv' (a nil value)
```
#### To Reproduce

1. Install Neovim version 0.9.5.
2. Install the plugin with Packer with
      ```lua
      -- packer.lua
      use {
          'xixiaofinland/sf.nvim',
          requires = {
              'nvim-treesitter/nvim-treesitter',
              'ibhagwan/fzf-lua',
          }
      }
      ```
      with default setup
      ```lua
      -- ~/.config/nvim/after/plugin/sf.lua
      require('sf').setup()
      ```
3. Execute command `:lua require'sf.util'.get_sf_root()`

#### Workaround
update Neovim to version 0.10.0

#### My thoughts
I think the issue is likely caused by the absence of `vim.uv` in Neovim versions below 0.10.0 as [this](https://github.com/neovim/neovim/issues/27957#issuecomment-2011030718) answer to a similar issue suggests and because updating the Neovim to version 0.10.0 solved the problem.

If this is the case, I don't know if it's fixable (I'm very new to Neovim and lua), but adding information in the [Prerequisites](https://github.com/xixiaofinland/sf.nvim?tab=readme-ov-file#-prerequisites) section about the required version number could be sufficient

I'm also new to Github Issues so if you need me to include more information, let me know

**Comment by xixiaofinland** [comment]
Hi, 

Thanks for mentioning this! Indeed `vim.uv` is introduced in v0.10 only. It can be easily replaced by `vim.loop`, supported by the older version.
However, I decide to keep the code unchanged and put v0.10 in the prerequisite section to motivate ppl use the latest version.
Nvim is moving forward rapidly and v0.10 stable version was already announced. There is really no reason to use v0.9x.

If more people demand the support of older versions, I will consider it again :).
