### ISSUE TITLE
SF Push error when deploying Page Layout 

### ISSUE THREAD

**Issue by ognjen-vuceljic** [xixiaofinland/sf.nvim#84]
Hello @xixiaofinland ,

hope you are doing well today!

Apologies if I am not using the plugin properly, but just wanted to bring an interesting situation to your attention:

**SCENARIO**

- I wanted to deploy Page Layout to the target org (only that file)
- I navigated to the Page Layout file directly in my SFDX project, and executed the `save and deploy` command

Here's the error I am receiving:

![Screenshot 2024-07-01 at 21 14 43](https://github.com/xixiaofinland/sf.nvim/assets/102177460/0503c5f5-722c-4bd1-bddd-13305deb30d5)

I exposed the object and layout name in the screenshot, so you can have a little bit more context. Not sure if `sf deploy` command needs to parse the full page layout name differently?

Apologies if this is not the bug, and it's just me not using the plugin as intended :) 

Looking forward to receiving feedback!

**Comment by xixiaofinland** [comment]
Hi @ognjen-vuceljic  thanks for creating the issue.
The pagelayout file has empty spaces in the middle of the name, resulting to the command line cutting the name into chunks.

I pushed a quick fix without proper testing. If you get the latest version, could you try to see if it works now?

**Comment by ognjen-vuceljic** [comment]
@xixiaofinland  Works well, thanks for the quick fix!

**Comment by xixiaofinland** [comment]
great! 
Thanks again to try sf.nvim out and submit this issue, without which I won't know this bug (I so far never encountered any file with blanks in the name).
