### ISSUE TITLE
SF Run Query - Run with selected text from visual mode

### ISSUE THREAD

**Issue by ognjen-vuceljic** [xixiaofinland/sf.nvim#94]
Hello,

thanks a lot for continuous improvements for this plugin!

Here's an idea that I have (similar feature, I think, exists in VS Code):

- run the SOQL query with the text that is selected in visual mode 

`sf data query --query "{this would be the selected text}"`

Example of usage:

![image](https://github.com/xixiaofinland/sf.nvim/assets/102177460/dbb772b7-0419-4ab1-bb0f-2395e7f52780)

Sometimes there is a need to quickly inspect data from the current org, without the need to create a separate file that would be a source for `SFRunQuery` command. 

Having the ability to execute a query by visually selecting SOQL portion from any file might speed some things up.

Apologies in advance if such feature already exists, or if it is hard to implement.

@xixiaofinland

**Comment by xixiaofinland** [comment]
Thanks for submitting this feature request!

It does look like a neat feature. Do you know how this works in VSCode, would you mind to elaborate the steps?

There are steps I don't have clear picture in mind yet. For example, once the highlighted SOQL runs, should it run in the terminal or background? Is the result the debug log or precisely the SQOL result? Should the result display in a new buffer/window or in the terminal?

**Comment by ognjen-vuceljic** [comment]
@xixiaofinland  Sure, please find the VS Code feature breakdown below:

1. Find the SOQL portion of the code, and highlight it (in this example, I've used the SOQL that is part of existing APEX class)

![Screenshot 2024-07-08 at 09 25 30](https://github.com/xixiaofinland/sf.nvim/assets/102177460/ac8c5c6b-41fc-46a9-8715-c87c9fff96bc)


Notice the "Execute SOQL With The Currently Selected Text" above - that's the VS Code shortcut that I can use whenever a portion of code is selected. This would probably be equivalent to the keymap in Neovim which would grab the selected code and put it in the `sf data query` command


2. Once this "Execute SOQL..." is selected , VS Code asks us about the mode in which we want to execute this query (aka which API to use)

![Screenshot 2024-07-08 at 09 28 05](https://github.com/xixiaofinland/sf.nvim/assets/102177460/4c5f68f2-3bdb-48a1-a86f-d96f78c8cdec)


3. The query results are simply written to the terminal, as they would if we executed this command directly via terminal instead of triggering the VS Code extension shortcut

![Screenshot 2024-07-08 at 09 28 20](https://github.com/xixiaofinland/sf.nvim/assets/102177460/7de24465-947d-4f54-97f9-24155707a56e)


For consistency sake, I would keep the output structure of this command the same as for any other SF command that we execute in the terminal. It's descriptive enough for us to understand what the end result was, and what are the rows that query returned.


I'd say that the key part here is an easy way for us to execute SOQL command regardless of where we are within our project structure. Having dedicated `.soql` files from which we can run existing SOQL command is nice and useful, but I think this would speed things up even more, and provide better user experience.

Hope this breakdown was useful - feel free to let me know if anything else is needed!

**Comment by xixiaofinland** [comment]
Appreciate for the clear description. This is clear for now. I will inform here once it's done.

**Comment by xixiaofinland** [comment]
a new `run_highlighted_soql()` (hotkey <leader>sq) is added.

The hotkey is enabled in visual mode only, it copies the selected text and pastes into the term as a SOQL.
Please test out.

**Comment by ognjen-vuceljic** [comment]
Thank you @xixiaofinland 

Initial tests are showing that `<leader>sq` executes the highlighted SOQL properly for both one-line and multi-line (formatted) queries.

There's just one UI/UX thing that I spotted:

![Screenshot 2024-07-11 at 14 03 42](https://github.com/xixiaofinland/sf.nvim/assets/102177460/003b73d1-adec-46a7-91a1-3ee33cc1f57c)

This query functionally worked, and produced expected results. However, the UI representation in the terminal appears to show some `command not found` messages.

**Comment by ognjen-vuceljic** [comment]
Thank you @xixiaofinland , now it looks ok :) 

Apologies, I had to edit the previous comment, as I initially didn't write that multi-line queries were affected.

Now both single and multi line queries are correctly visualized in terminal, and they both produce expected results.

**Comment by xixiaofinland** [comment]
great!
